# ============================================================
#  IRROPS Platform — GCP Setup Script (Windows PowerShell)
#  Run once to configure GCP + Python virtual environment
# ============================================================

param(
    [string]$ProjectId = "project-8fe939a0-6bb7-4abf-98e"
)

Write-Host ""
Write-Host "╔══════════════════════════════════════════════════╗" -ForegroundColor Cyan
Write-Host "║  IRROPS Platform — GCP Setup (Windows)           ║" -ForegroundColor Cyan
Write-Host "╚══════════════════════════════════════════════════╝" -ForegroundColor Cyan
Write-Host ""

# ── Step 1: Check prerequisites ───────────────────────────────────────────────
Write-Host "📋 Checking prerequisites..." -ForegroundColor Yellow

# Check Python
if (-not (Get-Command python -ErrorAction SilentlyContinue)) {
    Write-Host "❌ Python not found. Install from https://python.org/downloads" -ForegroundColor Red
    Write-Host "   Make sure to check 'Add Python to PATH' during install" -ForegroundColor Yellow
    exit 1
}
$pyVersion = python --version
Write-Host "  ✅ $pyVersion" -ForegroundColor Green

# Check Node
if (-not (Get-Command node -ErrorAction SilentlyContinue)) {
    Write-Host "❌ Node.js not found. Install from https://nodejs.org" -ForegroundColor Red
    exit 1
}
$nodeVersion = node --version
Write-Host "  ✅ Node.js $nodeVersion" -ForegroundColor Green

# Check gcloud
if (-not (Get-Command gcloud -ErrorAction SilentlyContinue)) {
    Write-Host "❌ gcloud CLI not found. Install from https://cloud.google.com/sdk/docs/install" -ForegroundColor Red
    exit 1
}
Write-Host "  ✅ gcloud CLI found" -ForegroundColor Green

# ── Step 2: Create Python virtual environment ─────────────────────────────────
Write-Host ""
Write-Host "🐍 Creating Python virtual environment..." -ForegroundColor Yellow

if (Test-Path ".venv") {
    Write-Host "  ℹ️  .venv already exists — skipping creation" -ForegroundColor Cyan
} else {
    python -m venv .venv
    Write-Host "  ✅ Virtual environment created" -ForegroundColor Green
}

Write-Host ""
Write-Host "  To activate the venv, run:" -ForegroundColor Cyan
Write-Host "  .venv\Scripts\Activate.ps1" -ForegroundColor White
Write-Host ""

# ── Step 3: GCP Authentication ────────────────────────────────────────────────
Write-Host "☁️  Setting up Google Cloud authentication..." -ForegroundColor Yellow
Write-Host ""
Write-Host "  This will open a browser for Google login." -ForegroundColor Cyan
Write-Host "  If browser doesn't open, use --no-launch-browser flag" -ForegroundColor Cyan
Write-Host ""

$response = Read-Host "  Press ENTER to continue with gcloud init, or 'S' to skip"
if ($response.ToUpper() -ne "S") {
    gcloud init
}

# ── Step 4: Application Default Credentials ───────────────────────────────────
Write-Host ""
Write-Host "🔑 Setting Application Default Credentials..." -ForegroundColor Yellow
Write-Host "   (This allows Python code to call Vertex AI, BigQuery etc.)" -ForegroundColor Cyan
Write-Host ""

gcloud auth application-default login `
    --scopes=https://www.googleapis.com/auth/cloud-platform `
    --no-launch-browser

# ── Step 5: Get project ID ────────────────────────────────────────────────────
if (-not $ProjectId) {
    $ProjectId = gcloud config get-value project
}

if (-not $ProjectId -or $ProjectId -eq "(unset)") {
    Write-Host ""
    $ProjectId = Read-Host "  Enter your GCP Project ID"
    gcloud config set project $ProjectId
}

Write-Host ""
Write-Host "  ✅ Project: $ProjectId" -ForegroundColor Green

# ── Step 6: Enable GCP APIs ───────────────────────────────────────────────────
Write-Host ""
Write-Host "🔌 Enabling required GCP APIs..." -ForegroundColor Yellow

$apis = @(
    "aiplatform.googleapis.com",
    "bigquery.googleapis.com",
    "pubsub.googleapis.com",
    "run.googleapis.com",
    "firestore.googleapis.com",
    "artifactregistry.googleapis.com"
)

foreach ($api in $apis) {
    Write-Host "   Enabling $api..." -NoNewline
    gcloud services enable $api --project=$ProjectId --quiet 2>$null
    Write-Host " ✅" -ForegroundColor Green
}

# ── Step 7: Create .env file ──────────────────────────────────────────────────
Write-Host ""
Write-Host "📝 Creating .env file..." -ForegroundColor Yellow

$envContent = @"
# IRROPS Platform Environment Variables
# Generated by setup-gcp.ps1

GCP_PROJECT_ID=$ProjectId
GCP_LOCATION=us-central1
GEMINI_MODEL=gemini-2.5-pro-preview-03-25
BQ_DATASET=irrops_audit
BQ_TABLE=audit_log
BQ_STREAM_TABLE=flight_streams
PUBSUB_TOPIC=irrops-events
CONFIDENCE_THRESHOLD=0.75
"@

$envContent | Out-File -FilePath ".env" -Encoding UTF8
Write-Host "  ✅ .env file created" -ForegroundColor Green

# ── Step 8: Set environment variables for this session ───────────────────────
$env:GCP_PROJECT_ID = $ProjectId
$env:GCP_LOCATION   = "us-central1"
$env:GEMINI_MODEL   = "gemini-2.5-pro-preview-03-25"

# ── Summary ───────────────────────────────────────────────────────────────────
Write-Host ""
Write-Host "╔══════════════════════════════════════════════════╗" -ForegroundColor Green
Write-Host "║  ✅ Setup Complete!                               ║" -ForegroundColor Green
Write-Host "╚══════════════════════════════════════════════════╝" -ForegroundColor Green
Write-Host ""
Write-Host "  Project ID : $ProjectId" -ForegroundColor White
Write-Host "  Region     : us-central1" -ForegroundColor White
Write-Host "  Model      : gemini-2.5-pro-preview-03-25" -ForegroundColor White
Write-Host ""
Write-Host "  Next steps:" -ForegroundColor Cyan
Write-Host "  1. Run: .\scripts\create-bigquery.ps1" -ForegroundColor White
Write-Host "  2. Activate venv: .venv\Scripts\Activate.ps1" -ForegroundColor White
Write-Host "  3. See docs\SETUP_GUIDE.md for full instructions" -ForegroundColor White
Write-Host ""
